### ISSUE TITLE
好像在1panel下跑不起来

### ISSUE THREAD

**Issue by 60999** [239573049/FastGateway#1]
```
报错日志：
【FreeSql: Master Database】Next recovery time：01/25/2024 13:04:57
Sql： select 1 from main.sqlite_master where type='table' and name='RouteEntity'
Unhandled exception. System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. unable to open database file
 ---> System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. unable to open database file
 ---> code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at FreeSql.Sqlite.DbConnectionExtensions.OpenAndAttach(DbConnection that, String[] attach)
   at FreeSql.Sqlite.SqliteConnectionPoolPolicy.OnGet(Object`1 obj)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeSchemaAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeSchemaAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at FreeSql.Internal.CommonProvider.Select0Provider`2..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Internal.CommonProvider.Select1Provider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.Curd.SqliteSelect`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.SqliteProvider`1.CreateSelectProvider[T1](Object dywhere)
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Select[T1]()
   at Program.<Main>$(String[] args) in /src/Gateway/Program.cs:line 73
   at Program.<Main>(String[] args)

```

```
networks:
    1panel-network:
        external: true
services:
    gateway-api:
        container_name: ${CONTAINER_NAME}
        environment:
            USER: root
            PASS: Aa010426.
        deploy:
            resources:
                limits:
                    cpus: '0'
                    memory: '0'
        image: registry.cn-shenzhen.aliyuncs.com/tokengo/gateway-api
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8200
        restart: always
        volumes:
            - ./data:/data
version: "3"

```

**Comment by 239573049** [comment]
是你的./data目录权限不够
导致sqlite的文件创建失败了

**Comment by GQ-Y** [comment]
docker命令直接跑跑不起来

**Comment by 239573049** [comment]
映射的目录最好是先创建，因为docker创建的映射目录会出现权限问题
