### ISSUE TITLE
找不到数据库文件

### ISSUE THREAD

**Issue by zenglei286** [239573049/FastGateway#2]
mkdir data
docker run -d --restart always --name gateway-api -p 8000:8000 -p 8200:8080 -p 8300:8081 -v $(pwd)/data:/data/ registry.cn-shenzhen.aliyuncs.com/tokengo/gateway-api
docker run -d --restart always --privileged --name gateway-web -p 10800:80 -e api_url=http://localhost:8000 registry.cn-shenzhen.aliyuncs.com/tokengo/gateway-web 按这个命令建立 了实例，但是在api的实例中出现了
【FreeSql: Master Database】Next recovery time：03/06/2024 09:37:52
Sql： select 1 from main.sqlite_master where type='table' and name='RouteEntity'
Unhandled exception. System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. unable to open database file
 ---> System.Exception: 【FreeSql: Master Database】Status unavailable, waiting for recovery. unable to open database file
 ---> code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at FreeSql.Sqlite.DbConnectionExtensions.OpenAndAttach(DbConnection that, String[] attach)
   at FreeSql.Sqlite.SqliteConnectionPoolPolicy.OnGet(Object`1 obj)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeSchemaAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeSchemaAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at FreeSql.Internal.CommonProvider.Select0Provider`2..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Internal.CommonProvider.Select1Provider`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.Curd.SqliteSelect`1..ctor(IFreeSql orm, CommonUtils commonUtils, CommonExpression commonExpression, Object dywhere)
   at FreeSql.Sqlite.SqliteProvider`1.CreateSelectProvider[T1](Object dywhere)
   at FreeSql.Internal.CommonProvider.BaseDbProvider.Select[T1]()
   at FastGateway.Program.Main(String[] args) in /src/src/FastGateway/Program.cs:line 131
   at FastGateway.Program.<Main>(String[] args)

**Comment by 239573049** [comment]
先执行sudo chmox 777 ./data 给与目录创建的权限，这个错误一般是生成sqlite的db文件失败了。
